nestjs/cqrs

- jest.config.js
- package-lock.json
- package.json
- src/command-bus.ts
- src/event-bus.ts
- src/index.ts
- src/interfaces/event-observable.interface.ts
- src/interfaces/index.ts
- src/interfaces/saga.type.ts
- src/operators/index.ts
- src/operators/of-type.spec.ts
- src/operators/of-type.ts
- src/utils/default-pubsub.ts
- src/utils/observable-bus.ts
```
[x] Bugfix
[ ] Feature
```
See issue:
Issue Number: https://github.com/nestjs/cqrs/issues/27
`ofType` now allows filtering multiple types of `IEvent`.
```
[] Yes
[x] No
```
Also fixes a conflict (yarn warnings) in packages and replace a few `any` by proper types.
> Resolves "Saga: 'ofType' has two different behaviors, the wrong one is exposed"

- src/command-bus.ts
- src/exceptions/command-not-found.exception.ts
help identifying which Command triggered the CommandHandlerNotFoundException
```
[ ] Bugfix
[x] Feature
[x] Refactoring (no functional changes, no api changes)
```
Currently, if the `CommandHandler` is not registered, only the following exception message is being raised `CommandHandler not found exception!`. It will help a bit to locate which Command actually triggered the exception.
Pass the `commandName` to the `CommandHandlerNotFoundException`
```
[ ] Yes
[X] No
```
> feat: pass the commandName to CommandHandlerNotFoundException

- src/aggregate-root.ts
Changes AggregateRoot's getEventHandler method access modifier from private to protected.
It will allow overwriting getEventHandler method in subclasses.
```
[x] Bugfix
[ ] Feature
```
It is not possible to overwrite AggregateRoot's getEventHandler method in subclass.
It is possible to overwrite AggregateRoot's getEventHandler method in subclass.
```
[ ] Yes
[x] No
```
> fix(): change aggregate root geteventhandler method access modifier

- src/event-bus.ts
> Where should I add the required tests ?
> Should I update the documentation to show usage with a method ?
```
[ ] Bugfix
[x] Feature
```
The `this` reference is lost when using a non-arrow function as saga.
The instance context is bound to the method within the event bus, upon registration.
We can now use decorated methods and keep access to the context
```
[ ] Yes
[x] No
```
In RxJs7, async iterators will be supported. As I am using it in my project, I wanted for the most simple sagas, to abstract the rxjs logic away.
```ts
class DomainSaga {
@ReactTo(EventA, …
```
> feat(saga): allow method style saga

- src/command-bus.ts
- src/interfaces/commands/command-bus.interface.ts
Changes ICommandBus and CommandBus execute method return type.
This allows to precisely specify the return value form CommandBus execute method.
```
[x] Bugfix
[ ] Feature
```
We can not specify return type from CommandBus execute method.
We can specify return type from CommandBus execute method.
```
[ ] Yes
[x] No
```
> fix(): add return type for command bus execute method promise

- src/aggregate-root.ts
- src/event-publisher.ts
Using publishAll() instead of publish() enables implementations of IEventBus to
support correct transactional semantics when used together with EventPublisher.
```
[x] Bugfix
[ ] Feature
```
`AggregateRoot`'s current `commit()` implementation invokes `publish()` instead of a `publishAll()`, This prevents `IEventPublisher.publishAll()` from ever being called which breaks transactional semantics when publishing events to an `IEventPublisher` implementation. 
Issue Number: #325
A new `publishAll()` method …
> fix: Change AggregateRoot's commit() to use publishAll()

- .eslintrc.js
- src/aggregate-root.ts
- src/command-bus.ts
- src/query-bus.ts
prettier/@typescript-eslint is now a part
of the prettier rules.
Removed errors produced the Function type.
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
`npm run lint` returns
```
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
```
lint passes
```
[ ] Yes
[x] No
```
> refactor(): fix not working eslint

- package.json
- src/command-bus.ts
- src/decorators/command-handler.decorator.ts
- src/decorators/constants.ts
- src/decorators/query-handler.decorator.ts
- src/interfaces/commands/command-metadata.interface.ts
- src/interfaces/queries/query-metadata.interface.ts
- src/query-bus.ts
Previously, the handler for command/query (action) was assigned by the
action name. When there were multiple actions with the same name
handlers were overwritten.
Use ids to differentiate actions with the same name.
Closes @nestjs/cqrs#787
```
[x] Bugfix
[ ] Feature
```
Issue Number: #787
```
[ ] Yes
[x] No
```
> fix(): don't resolve handlers based on names

- src/decorators/constants.ts
- src/decorators/events-handler.decorator.ts
- src/event-bus.ts
- src/helpers/default-get-event-id.ts
- src/helpers/default-get-event-name.ts
Add id to every event class to make it possible
to distinguish between events with the same name.
Closes #790
When we have two events with the same name and each of them has its own handlers then when any of them is published all of those handlers will be executed.
Issue Number: #790
Only handlers registered for the specific class are executed.
> fix(event-bus): distinguish between events

- src/event-bus.ts
- src/helpers/default-get-event-id.ts
Handle case when a class without
any handler was published.
Closes #924
Issue Number: 924
> fix(event-bus): event id is optional

- src/event-bus.ts
Log errors produced by an event handler
and by a saga as they crash the app.
Refs #409
Issue Number: 409
> feat(event-bus): log subscription errors

- src/decorators/events-handler.decorator.ts
The handler for an event inheriting a base event will be called twice, once for the child class, another time for the base class
```ts
abstract class AbstractEvent {}
class ConcreteEvent extends AbstractEvent {}
@EventsHandler(ConcreteEvent)
export class ConcreteEventHandler implements IEventHandler<ConcreteEvent> {
constructor(private readonly repository: InvoiceEventPrismaCommandRepository) {}
async handle(args: AbstractEvent) {
// this is called twice
}
}
```
The handler is only called once
> fix(event-bus): support events extending a base class

- src/decorators/command-handler.decorator.ts
- src/decorators/query-handler.decorator.ts
When there is two commands/queries that one inherits from the other and both of them have registered handlers, then metadata for them is defined only for parent and not for child. This causes the same ID to be generated for both commands/queries, sometimes resulting in wrong handler picking up the message.
Take a look at this example:
```
class ParentCommand {
constructor(public readonly foo: string) {}
}
class ChildCommand extends ParentCommand {}
@CommandHandler(ParentCommand)
class ParentCommandHandler implements ICommandHandler<ParentCommand> {
// ...
}
@CommandHandler(ChildCommand)
class ChildCommandHandler implements ICommandHandler<ChildCommand> {
// ...
}
```
Snippet of …
> fix(decorators): check for own metadata in command/query handler

- src/decorators/command-handler.decorator.ts
I extended `ICommand` interface via TypeScript's Declaration Merging, adding own properties there, so that I can enforce all my commands to adhere to some standard format. This made my code not compile due to invalid/incomplete typing for `CommandHandler` decorator, which expects `ICommand` *instance* passed as an argument, while the documented intention is that it accepts `ICommand`-compatible *type*.
I extended the existing typing so that the actual class type that implements `ICommand` is accepted by `CommandHandler` decorator.
> style(cqrs): fix typing for CommandHandler to actually accept the type of class extending ICommand

- src/decorators/events-handler.decorator.ts
I extended IEvent interface via TypeScript's Declaration Merging, adding own properties there, so that I can enforce all my events to adhere to some standard format. This made my code not compile due to invalid/incomplete typing for EventsHandler decorator.
I believe IEvent interface should have ability to be extendible in same manner as ICommand became extendible with [this PR](https://github.com/nestjs/cqrs/pull/1206).
I extended the existing typing so that the actual class type that implements IEvent is accepted by EventsHandler decorator.
> style(cqrs): fix typing for EventsHandler to accept the type of class extending IEvent

- src/cqrs.module.ts
- src/event-bus.ts
- src/helpers/default-unhandled-exception-pubsub.ts
- src/index.ts
- src/interfaces/exceptions/unhandled-exception-info.interface.ts
- src/interfaces/exceptions/unhandled-exception-publisher.interface.ts
- src/interfaces/index.ts
- src/unhandled-exception-bus.ts
Provides the `UnhandledExceptionBus` injectable that lets you react to unhandled exceptions that were thrown from either event handlers or sagas:
```typescript
private readonly destroy$ = new Subject<void>();
constructor(private readonly unhandledExceptionsBus: UnhandledExceptionBus) {
this.unhandledExceptionsBus
.pipe(takeUntil(this.destroy$))
.subscribe((exceptionInfo) => {
// Handle exception here
// e.g. send it to external service, terminate process, or publish a new event
});
}
onModuleDestroy() {
this.destroy$.next();
this.destroy$.complete();
}
```
To filter out stream and subscribe to a specific exception type, use the `UnhandledExceptionBus.ofType` operator, as follows: …
> feat: add unhandled exceptions bus

- src/operators/of-type.spec.ts
- [] Docs have been added / updated (for bug fixes / features)
```
> @nestjs/cqrs@10.2.6 test
> jest
FAIL  src/operators/of-type.spec.ts
● Test suite failed to run
src/operators/of-type.spec.ts:35:17 - error TS2556: A spread argument must either have a tuple type or be passed to a rest parameter.
35     stream.next(...expectedResults);
~~~~~~~~~~~~~~~~~~
Test Suites: 1 failed, 1 total                                                                                                                                                                               
Tests:       0 total …
```
> test: fix type error in of-type.spec.ts

- src/operators/of-type.spec.ts
- src/operators/of-type.ts
```
[x] Bugfix
[ ] Feature
```
When using `ofType` with more than one type it would try to collapse those down into a single type, ie `A | B` would become A if B was essentially the same as A but with a few extra properties. And if the types couldn't be collapsed because they were incompatible then you would just get an error requiring the generics to be manually filled int
The `ofType()` can now property infer types of unions wether they are similar or disparate
```
[x] Yes
[ ] No …
```
> fix: type inference of type

- src/cqrs.module.ts
- src/decorators/index.ts
- src/decorators/publishable.decorator.ts
- src/storages/aggregate-root.storage.ts
Issue Number: #1466
Added the `@Publishable()` decorator that holds the decorated class to the internal storage to merge them with the event publisher on the application bootstrap.
> Add publishable decorator to automatically merge publisher into decorated AggregateRoot

- package-lock.json
- package.json
- src/decorators/command-handler.decorator.ts
- src/decorators/events-handler.decorator.ts
- src/decorators/query-handler.decorator.ts
The `crypto` global is available in all supported Node.js versions as well as [in all major browsers](https://caniuse.com/mdn-api_crypto_randomuuid). The uuid module is rendered unnecessary for uuidv4.
`@nestjs/graphql` is currently downloaded about 580000 times per week, so about 30740000 times per year. `uuid@11` is about 3.7 kB in size (gzipped+minified). Removing this dependency saves about 113GB traffic per year.
> chore(deps): Use `crypto.randomUUID()` instead of `uuid` module

- src/event-bus.ts
if undefined, fallback to handler.metadata
Cannot register an EventHandler on EventBus With NestJs 11.x
[Issue Number: N/A](https://github.com/nestjs/cqrs/issues/1908)
Instead of using handler.metadata, we should retrieve a constructor reference from handler.instance and use it instead. Only if it's undefined, then we should fallback to handler.metadata
> fix(eventbus): Use a constructor reference from handler.instance

- src/cqrs.module.ts
- src/interfaces/cqrs-module-options.interface.ts
---
---
Issue Number: 1912
- The CQRS module was not dynamically configurable with `useFactory` to inject dependencies.
---
- Refactored the `CqrsModule` to support dynamic async provider configuration using `useFactory`.
- Added the ability to inject dependencies into the factory function and make `CQRS_MODULE_OPTIONS` configurable.
- Ensured that `CQRS_MODULE_OPTIONS` can be injected from a separate module if required, improving modularity and flexibility.
---
---
- This update ensures that configuration options for the CQRS module can be set asynchronously, which allows for more flexible and scalable configuration, especially in dynamic environments
> feat(module): add forRootAsync method for dynamic configuration
